# ================================================================================
# 📊 Codecov 設定ファイル
# ================================================================================
# このファイルは、Codecov サービスの動作をカスタマイズします
# Codecov は GitHub Actions から送信されたテストカバレッジデータを受け取り、
# 以下の機能を提供します：
# - カバレッジ率の推移を追跡
# - Pull Request に自動コメント
# - カバレッジ低下時に警告
# ================================================================================

# ================================================================================
# 🎯 カバレッジの最小値（必須チェック）
# ================================================================================
coverage:
  # このしきい値を下回るとチェック失敗
  precision: 2           # 小数第2位まで表示
  round: down            # 切り捨て
  range: '70...100'      # 許容範囲：70% ～ 100%

# ================================================================================
# 📝 Pull Request への自動コメント
# ================================================================================
comment:
  layout: 'reach, diff, flags, tree'
  behavior: default              # ファイル変更時のみコメント
  require_changes: false         # 変更がなくてもコメント
  require_base: true             # ベースブランチとの比較を必須
  require_head: true             # HEAD との比較を必須

# ================================================================================
# 🎨 カバレッジの表示設定
# ================================================================================
ui:
  # Codecov.io ダッシュボードでの表示設定
  url: 'https://app.codecov.io'

# ================================================================================
# 🔍 解析対象外ファイル
# ================================================================================
ignore:
  - 'node_modules'
  - 'dist'
  - 'coverage'
  - '**/*.d.ts'
  - '**/*.config.ts'
  - 'src/test'
  - 'src/**/*.test.ts'
  - 'src/**/*.test.tsx'
  - 'src/**/*.spec.ts'
  - 'src/**/*.spec.tsx'

# ================================================================================
# 📊 ステータスチェック設定
# ================================================================================
# カバレッジチェックの成功・失敗を判定
# ================================================================================
status:
  # 全体のカバレッジチェック
  project:
    default:
      target: 70              # 目標：70% 以上
      threshold: 5            # 低下許容範囲：-5%
      base: auto              # ベースブランチと比較

    # ブランチ別の設定
    main:
      target: 80              # main ブランチはより厳しく
      threshold: 2            # 低下許容範囲：-2%

  # パッチ（変更部分）のみのチェック
  patch:
    default:
      target: 80              # パッチは高い基準を要求
      threshold: 3            # 低下許容範囲：-3%

  # フラグ別チェック
  changes:
    default:
      target: 80              # 変更されたファイルは 80% 以上
      threshold: 3

# ================================================================================
# 🏷️ フラグ設定
# ================================================================================
# 異なるテストグループを分類
# ================================================================================
flags:
  unittests:
    carryforward: true         # 前回のデータを引き継ぎ
    paths:
      - 'src/**/*.test.ts'
      - 'src/**/*.test.tsx'

  e2e:
    carryforward: true
    paths:
      - 'tests/e2e/**'

# ================================================================================
# 🔔 通知設定
# ================================================================================
notify:
  # Slack へ通知（設定時）
  slack:
    default:
      url: $SLACK_WEBHOOK_URL  # 環境変数から取得
      threshold: 5             # 5% 以上の変化で通知

# ================================================================================
# 🔄 フォールバック設定
# ================================================================================
# エラー時の動作
# ================================================================================
require: true                  # アップロード失敗時はチェック失敗
max_retries: 3                 # リトライ回数
use_legacy: false              # 新しい API を使用

# ================================================================================
# 📝 コメント設定（詳細）
# ================================================================================
comment:
  # PR コメントに含める情報
  # - reach: カバレッジ到達範囲
  # - diff: 差分ファイルのカバレッジ
  # - flags: フラグ別の統計
  # - tree: ファイルツリー表示
  layout: 'reach,diff,flags,tree'

  # コメント内容
  require_changes: false       # 変更なくてもコメント
  require_base: true           # ベースブランチとの比較必須
  require_head: true           # HEAD との比較必須

  # アーカイブ設定
  after: update                # コメント作成後に更新
  default: 'Changes'           # デフォルトコメント文言

  # 条件付きコメント
  if_head: true
  if_base: true
  if_pr: true
  if_commit: false
  if_author: true
